version: '3'

services:
  traefik:
    image: traefik:v2.2  
    container_name: traefik
    ports:
      - "${HTTP_PORT:-80}:${HTTP_PORT:-80}"
      - "${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
      - "8080:8080"
    volumes: 
      - ./traefik/config:/config
      - ./certificates:/certificates
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    labels:
      - "traefik.enable=true"
    command:
      - "--global.sendanonymoususage=false"
      - "--log=true"
      - "--log.level=${LOG_LEVEL:-INFO}"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/config"
      - "--entryPoints.http=true"
      - "--entryPoints.https=true"
      - "--entryPoints.http.address=:${HTTP_PORT:-80}"
      - "--entryPoints.https.address=:${HTTPS_PORT:-443}"

  tmd-server:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.7
    container_name: tmd-server-dev
    restart: always
    volumes:
      - './app:/app'
    command:
      -  "${SERVER_COMMAND:-/start-reload.sh}"
    labels:     
      - "traefik.enable=true" 
      # - "traefik.http.routers.tmd-server.rule=Host(`${TMD_HOST:?Please provide TMD_HOST in the environment}`)"
      # - "traefik.http.routers.tmd-server.entrypoints=http"
      # - "traefik.http.routers.tmd-server.middlewares=redirect-to-https"
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.port=${HTTPS_PORT:-443}"
      - "traefik.http.routers.tmd-server-secured.rule=Host(`${TMD_HOST}`)"
      - "traefik.http.routers.tmd-server-secured.entrypoints=https"
      - "traefik.http.routers.tmd-server-secured.tls=true"
      - "traefik.http.routers.tmd-server-secured.tls.options=default"