version: '3'

# See: https://docs.traefik.io/providers/docker/
# - and: https://docs.traefik.io/routing/providers/docker/
# TODO: protect socket
# - see https://docs.traefik.io/providers/docker/#docker-api-access
# Env variables in ./.env see https://docs.docker.com/compose/environment-variables/   
services:
  traefik:
    image: traefik:v2.2  
    container_name: traefik
    ports:
      - "${HTTP_PORT}:8000"
      - "${HTTPS_PORT}:4430"
      - "8080:8080"
    volumes: 
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/dyn.toml:/dyn.toml
      - ./certs/192.168.1.143.key:/certs/192.168.1.143.key
      - ./certs/192.168.1.143.pem:/certs/192.168.1.143.pem
      - ./certs/client/CA.pem:/certs/client/CA.pem
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.api.entryPoints=api"
      #- "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      #- "traefik.http.routers.api.service=api@internal"
      #- "traefik.http.routers.api.middlewares=api-auth"
      #- "traefik.http.middlewares.api-auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/"

  tmd-server:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.7
    container_name: tmd-server-dev
    restart: always
    volumes:
      - './app:/app'
    command:
      -  /start-reload.sh
    labels:     
      - "traefik.enable=true" 
      - "traefik.http.routers.tmd-server.rule=Host(`192.168.1.143`)"
      - "traefik.http.routers.tmd-server.entrypoints=http"
      - "traefik.http.routers.tmd-server.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.port=${HTTPS_PORT}"
      - "traefik.http.routers.tmd-server-secured.rule=Host(`192.168.1.143`)"
      - "traefik.http.routers.tmd-server-secured.entrypoints=https"
      - "traefik.http.routers.tmd-server-secured.tls=true"
      - "traefik.http.routers.tmd-server-secured.tls.options=default"