name: accelerometertest
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sensors: any
  intl: any
  slugify: any
  flutter_map: any
  location: ^2.5.0
  path_provider: any
  shared_preferences: any
  preferences: ^5.1.0
  connectivity: any
  dio: ">=3.0.1 < 4.0.0"
  filesize: any
  provider: any
  cupertino_icons: ^0.1.2
  battery: ">=0.3.1+9 <2.0.0"
  async:
  quiver:
  device_info:
  geolocator: ^5.3.1
  foreground_service:
    path: ./plugins/foreground_service
  background_locator: ^1.1.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter:
  uses-material-design: true
  assets:
    - assets/certificates/
    - assets/certificates/public-keys/
    - assets/server-info.json

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"